### ISSUE TITLE
CBCT2CT on full 512 dicom volumes

### ISSUE THREAD

**Issue by jerichooconnell** [nadeemlab/Physics-ArX#2]
Hello! Wonderful code thanks for sharing. And thanks for taking the time to explain how to use it, I found the explanation very helpful. 

My question is as follows: I can import new CBCT volumes and crop them to 128 cubes for input into the network, I do this to preserve the initial resolution. But I would like to convert the whole dicom volume. Is the best way to do this to input many 128 cubes and stitch them together, what would be the method that you recommend for this use case?

If I were to try and stitch together whole dicom volume I am not sure how to scale the images. Should I rescale using the global max and min of the dicom volume or the individual max and mins of each 128 cube, have you ever tried this?

Many thanks! -Jericho

**Comment by sanadeem** [comment]
Thank you, Jericho!

We haven't tried this. I would try max/mins of each 128 cube but not sure since this is not the intended use of the model. Would love to hear if you were able to make it work though. 

Ideally, you would want to retrain the CBCT2CT model with full 512 resolution (this perhaps can only be done with an A100 80GB NVIDIA GPU). With our A40 (48GB memory), we were able to train up till 256 cube resolution (not specifically for this model though). In the context of radiotherapy, I haven't seen CBCT images that are full 512 cube resolution. Normally, they are acquired with a narrower field-of-view than planning CT images (which can be full 512 resolution).

**Comment by jerichooconnell** [comment]
Sweet, thank you for your quick reply! I see now the limitation of the 3d network in terms of memory.

Yes I think my registered CBCTs are generally 512x512x164 so I doubt I would ever need the full cube. Perhaps it would be of interest to me to try for a 512x512x16 as I think perhaps stitching along the z-axis would look better if there were non-uniformities.

I'll get back to you on how the stitching goes. Thanks again!

**Comment by sanadeem** [comment]
As opposed to the 3D version, you can also modify our architecture to train a 2D CBCT2CT for your full 512x512 slices. In this case, you will run the model slice by slice. There might be some discrepancies across slices but might not be too bad. In our case, it was important to do 3D because we were segmenting esophagus as well which fails miserably if done in 2D due to the tubular topology.

**Comment by jerichooconnell** [comment]
Yes perhaps at some point I will look into a different architecture with perhaps a 512 slice layer. 

Stitching works better than expected! The uniformity is increased and major motion artifacts are reduced which is what I wanted to improve my dose calculation. And hopefully the sCT values will work with the MC dose calc. Here is a gif of the lung case:

![ML_corr_full](https://user-images.githubusercontent.com/31938913/188028892-6d855124-8ecc-42e0-abdb-511af0b66c41.gif)

**Comment by sanadeem** [comment]
Wow this looks better than what I expected. If you don’t mind, can you please put up a pull request with the details of how you were able to do this added to the main readme at the end along with these gifs added in the images sub-folder. Hopefully other people will be able to benefit from your experience as well and you will get credit for this on the repo.

**Comment by jerichooconnell** [comment]
Thanks for the kind words! Yes I'll send a pull request soon.
